services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: dbank_postgres
    environment:
      POSTGRES_USER: dbank_user
      POSTGRES_PASSWORD: dbank_pass_2025
      POSTGRES_DB: dbank
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbank_user -d dbank"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: