# dbt_project.yml
name: 'dbank_copilot'
version: '1.0.0'
config-version: 2

profile: 'dbank_copilot'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data_tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbank_copilot:
    # Staging models - materialized as views
    staging:
      +materialized: view
      +schema: staging
      
    # Mart models - materialized as tables for performance
    marts:
      +materialized: table
      +schema: marts


# Test configurations
tests:
  dbank_copilot:
    +store_failures: true
    +schema: test_results

# Variables (can be overridden)
vars:
  # Date ranges for incremental models
  start_date: '2022-01-01'
  end_date: '2025-12-31'