# dbt_project/profiles.yml
# dbt profile configuration for dBank Copilot

dbank_copilot:
  target: dev
  
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dbank_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dbank_pass_2025') }}"
      database: "{{ env_var('POSTGRES_DB', 'dbank') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dbank_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dbank_pass_2025') }}"
      database: "{{ env_var('POSTGRES_DB', 'dbank') }}"
      schema: analytics
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10